<?
$PERM["obnovit-brend.php"]["*"]="D";
$PERM["obnovit-brend.php"]["6"]="X";
$PERM["developers"]["*"]="D";
$PERM["developers"]["G1"]="X";
$PERM["import-polzovateley"]["*"]="D";
$PERM["import-polzovateley"]["6"]="X";
$PERM["personal"]["7"]="W";
$PERM["catalog"]["7"]="W";
$PERM["news"]["7"]="W";
$PERM["about"]["7"]="W";
$PERM["index.php"]["7"]="W";
$PERM["/"]["*"]="R";
?>